### ISSUE TITLE
Tür Sensor

### ISSUE THREAD

**Issue by salopette** [heggink/domoticz-nuki#4]
Hi, is it possible to integrate status of the magnet door sensor from the Nuki into the domoticz?

**Comment by heggink** [comment]
I could take a look at it. If the API supports updates then it would definitely be possible. I don;t have a V2 myself so would rely on you to help me test it.
Looking at the API, I did not see any reference to the door sensor. Looking at this thread (https://developer.nuki.io/t/bridge-api-door-sensor/422/12), the door sensor is not implemented in their API and they don't seem to have a date for it. It may not even make the bridge API and would need the web API which would be a complete new development. I am not a big fan of the web API to begin with because it would require a lot stronger security then when you work within your own network (the assumption for the plugin was that domoticz and nuki would sit on the same network inside your control).
I'll keep a look out for an enhanced HTTP API.

**Comment by heggink** [comment]
StephaneM60 has created a new pull request to add teh door sensor to the plugin. It's now available in the feature-unlatch branch. Please note taht the device numbers have been changed so the plugin will create new devices and you need to delete the old ones..
